version: '3'
services:
  web:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ${PROJECT_PATH:-./src}:/var/www/html
      - ./logs/nginx:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/cert-key:/etc/nginx/ssl
    ports:
      - ${WEB_PORT:-10080}:80
      - ${SSL_PORT:-10443}:443
  app:
    build:
      context: ./docker/php
      args:
        - TZ=${TZ:-Asia/Tokyo}
    depends_on:
      - db
    volumes:
      - ${PROJECT_PATH:-./src}:/var/www/html
      - ./docker/ash:/etc/profile.d
      - ./docker/php/psysh:/root/.config/psysh
      - ./logs/php:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - ${APP_PORT:-18000}:8000
  db:
    image: mysql:5.7
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_NAME:-homestead}
      - MYSQL_USER=${DB_USER:-homestead}
      - MYSQL_PASSWORD=${DB_PASS:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-secret}
    ports:
      - ${DB_PORT:-13306}:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    volumes:
      - ./.data/phpmyadmin/sessions:/sessions
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=db
      - PMA_USER=${DB_USER:-homestead}
      - PMA_PASSWORD=${DB_PASS:-secret}
    ports:
      - ${PMA_PORT:-50800}:80
